# -*- coding: utf-8 -*-
"""Desafio-14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lwdrG-ThNlIYxBj5Og9WQxpDif15rTc

Nome: Luiz Fernando de Oliveira Pereira
RA: 267356
"""

# 1. Importe o conjunto de dados diamonds, cujo arquivo está disponível no website da disciplina.

# Importa a biblioteca principal do plotnine
from plotnine import *

# Importa o conjunto de dados diamonds diretamente do módulo plotnine.data
from plotnine.data import diamonds

# Visualiza as primeiras linhas para confirmar o carregamento
print(diamonds)

!pip install reportlab

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle, StyleSheet1
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Preformatted
from datetime import datetime
from plotnine import *
from plotnine.data import diamonds

# ========== 1. GERA OS GRÁFICOS ==========
# Gráfico 1: Associação entre peso e preço
grafico1 = (
    ggplot(diamonds, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.6, size=2) +
    geom_smooth(method='lm', se=False, linetype='dashed') +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_brewer(type='qual', palette='Set2') +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +
    labs(
        title='Associação entre Peso (Carat) e Preço (USD) dos Diamantes (Escala Log)',
        x='Peso (em quilates) - escala log',
        y='Preço (em dólares) - escala log',
        color='Qualidade do Corte',
        shape='Qualidade do Corte'
    ) +
    theme_minimal() +
    theme(legend_position='right', figure_size=(10, 6))
)
grafico1.save("grafico1.png", dpi=300)

# Gráfico 2: Relação entre peso e preço por tipo de corte
diamonds_filtered = diamonds.query("price <= 20000")
grafico2 = (
    ggplot(diamonds_filtered, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.3, size=1.5, show_legend=False) +
    geom_smooth(method='lm', se=False, color='black', linetype='dashed') +
    facet_wrap('~cut') +
    labs(
        title='Relação entre Peso (Carat) e Preço (USD) por Tipo de Corte',
        x='Peso (em quilates)',
        y='Preço (em dólares)'
    ) +
    scale_y_continuous(limits=(0, 20000)) +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +
    theme_minimal() +
    theme(figure_size=(10, 6))
)
grafico2.save("grafico2.png", dpi=300)

# Gráfico 3: Peso e preço considerando corte, cor e clareza
grafico3 = (
    ggplot(diamonds, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.3, size=0.8) +
    geom_smooth(method='lm', se=False, linetype='dashed', color='black') +
    facet_grid('color ~ clarity') +
    scale_y_continuous(limits=(0, 20000)) +
    scale_color_brewer(type='qual', palette='Set2') +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +
    labs(
        title='Relação entre Peso (Carat) e Preço (USD) por Corte, Cor e Clareza',
        subtitle='Cada painel representa uma combinação de cor (linhas) e clareza (colunas)',
        x='Peso (em quilates)',
        y='Preço (em dólares)',
        color='Corte',
        shape='Corte'
    ) +
    theme_minimal() +
    theme(
        legend_position='bottom',
        text=element_text(size=9),
        figure_size=(14, 10),
        subplots_adjust={'wspace': 0.15, 'hspace': 0.3}
    )
)
grafico3.save("grafico3.png", dpi=300)

# ========== 2. MONTA O PDF ==========
pdf = SimpleDocTemplate("desafio_14.pdf", pagesize=A4,
                        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)

styles = getSampleStyleSheet()
# Create a new stylesheet object by copying the sample stylesheet
custom_styles = StyleSheet1()
for attr, value in styles.__dict__.items():
    if isinstance(value, ParagraphStyle):
        custom_styles.add(value)

custom_styles.add(ParagraphStyle(name='Title', fontSize=14, leading=16, spaceAfter=10, alignment=1))
custom_styles.add(ParagraphStyle(name='Text', fontSize=11, leading=14, spaceAfter=10))
custom_styles.add(ParagraphStyle(name='Code', fontName='Courier', fontSize=9, leading=11, backColor=colors.whitesmoke))

# Lista de elementos do PDF
conteudo = []

# Título
conteudo.append(Paragraph("<b>Desafio 14 - Visualização de Dados (Diamonds Dataset)</b>", custom_styles['Title']))
conteudo.append(Spacer(1, 12))

# Questão 1
conteudo.append(Paragraph("<b>1. Importe o conjunto de dados diamonds, cujo arquivo está disponível no website da disciplina.</b>", custom_styles['Text']))
conteudo.append(Spacer(1, 8))
conteudo.append(Paragraph("O conjunto de dados foi importado diretamente do módulo <i>plotnine.data</i>.", custom_styles['Text']))
conteudo.append(Spacer(1, 16))

# Questão 2
conteudo.append(Paragraph("<b>2. Associação entre peso (carat) e preço (price)</b>", custom_styles['Text']))
conteudo.append(Spacer(1, 8))
conteudo.append(Image("grafico1.png", width=400, height=250))
conteudo.append(Spacer(1, 10))
conteudo.append(Paragraph("""
O gráfico de dispersão mostra uma relação positiva entre o peso (carat) e o preço dos diamantes.
À medida que o peso aumenta, o preço tende a crescer proporcionalmente. Para melhorar a visualização,
foram usadas diferentes cores e formas geométricas para cada corte, além da escala logarítmica,
devido ao grande número de pontos (mais de 50.000). Nota-se que a dispersão dos preços aumenta em
diamantes mais pesados, o que sugere que outros fatores como clareza e cor influenciam o preço de pedras maiores.
""", custom_styles['Text']))
conteudo.append(Spacer(1, 16))

# Questão 3
conteudo.append(Paragraph("<b>3. Relação entre peso e preço nos diferentes cortes de diamantes</b>", custom_styles['Text']))
conteudo.append(Spacer(1, 8))
conteudo.append(Image("grafico2.png", width=400, height=250))
conteudo.append(Spacer(1, 10))
conteudo.append(Paragraph("""
A visualização em facetas evidencia que a relação positiva entre peso e preço se mantém em todos os tipos de corte.
As retas indicam inclinações similares e positivas, mostrando que quanto maior o peso, maior o preço.
A separação por tipo de corte facilita a comparação entre as categorias.
""", custom_styles['Text']))
conteudo.append(Spacer(1, 16))

# Questão 4
conteudo.append(Paragraph("<b>4. Relação entre preço e peso considerando corte, cor e clareza</b>", custom_styles['Text']))
conteudo.append(Spacer(1, 8))
conteudo.append(Image("grafico3.png", width=400, height=300))
conteudo.append(Spacer(1, 10))
conteudo.append(Paragraph("""
A principal dificuldade está em comparar os 56 painéis simultaneamente,
o que exige mais tempo para análise. Apesar disso, é possível observar
que a relação positiva entre preço e peso se mantém, com pequenas variações
em alguns painéis. O tamanho reduzido dos textos e gráficos também torna a leitura mais desafiadora.
""", custom_styles['Text']))

# Data e hora de geração
agora = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
conteudo.append(Spacer(1, 20))
conteudo.append(Paragraph(f"<b>PDF gerado em:</b> {agora}", custom_styles['Text']))

# Construção do PDF
pdf.build(conteudo)
print("✅ PDF 'desafio_14.pdf' gerado com sucesso!")

# 2.Crie uma visualização de dados que descreva a associação existente entre as variáveis peso (carat) e preço (price). Que ações você tomou para garantir que você produziu um gráfico de boa qualidade? Escreva um parágrafo comunicando os seus achados.


from plotnine import *
from plotnine.data import diamonds

(
    ggplot(diamonds, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.6, size=2) +
    geom_smooth(method='lm', se=False, linetype='dashed') +
    scale_x_log10() +  # Escala log no eixo X
    scale_y_log10() +  # Escala log no eixo Y
    scale_color_brewer(type='qual', palette='Set2') +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +
    labs(
        title='Associação entre Peso (Carat) e Preço (USD) dos Diamantes (Escala Log)',
        x='Peso (em quilates) - escala log',
        y='Preço (em dólares) - escala log',
        color='Qualidade do Corte',
        shape='Qualidade do Corte'
    ) +
    theme_minimal() +
    theme(
        legend_position='right',
        figure_size=(10, 6),
        text=element_text(size=11)
    )
)

# O gráfico de dispersão abaixo mostra uma relação positiva entre o peso(carat) e o preço dos diamantes, percebe-se que à medidade que o peso aumenta, o preço tende a crescer proporcionalmente.
# Para tentar garantir uma visualização melhor, acrescentei diferente tipos de cores e diferente formas geométricas para cada corte, além de deixar na escala log devido a quantidade de pontos(mais de 50.000)
# E também nota-se qie a dispersão dos preços aumenta significativamente em diamantes mais pesados, o que indica que outros fatores como a clareza e a cor talvez ganhem maior influência na preficicação de pedras maiores

# 3.A relação identificada na questão anterior é a mesma relação presente nos diferentes cortes de diamantes? Crie uma visualização que demonstre seus achados eficientemente. Descreva sua conclusão em um parágrafo.

# Filtra valores até 20.000 para manter consistência com o gráfico anterior
diamonds_filtered = diamonds.query("price <= 20000")

(
    ggplot(diamonds_filtered, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.3, size=1.5, show_legend=False) +  # aumentei um pouco o tamanho para ver as formas
    geom_smooth(method='lm', se=False, color='black', linetype='dashed') +
    facet_wrap('~cut') +
    labs(
        title='Relação entre Peso (Carat) e Preço (USD) por Tipo de Corte',
        x='Peso (em quilates)',
        y='Preço (em dólares)'
    ) +
    scale_y_continuous(limits=(0, 20000)) +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +  # círculo, triângulo, quadrado, diamante, X
    theme_minimal() +
    theme(
        figure_size=(10, 6),
        text=element_text(size=10)
    )
)


# Aqui a visualização em facetas ajuda a evidenciar que a relação positiva entre peso e preço se mantém consistente em todos os tipos de cortes, mas com algum extremos.
# Como todas as retas indicam inclinações similares e positivas, afirmando que quanto maior o peso, maior o preço
# A separação de cada gráfico por tipo de corte facilitou a visualização e ajudou na comparação entre as categorias.



"""# COLOCAR AS FORMAS GEOMÉTRICAS

"""

# 4. Crie uma visualização que mostre a relação entre preço e peso do diamante, considerando as diferentes combinações de qualidade de corte, cor e clareza do diamante. Quais foram as dificuldades encontradas? A relação entre preço e peso é a mesma para diferentes configurações de diamantes?


(
    ggplot(diamonds, aes(x='carat', y='price', color='cut', shape='cut')) +
    geom_point(alpha=0.3, size=0.8) +
    geom_smooth(method='lm', se=False, linetype='dashed', color='black') +
    facet_grid('color ~ clarity') +
    scale_y_continuous(limits=(0, 20000)) +
    scale_color_brewer(type='qual', palette='Set2') +
    scale_shape_manual(values=['o', '^', 's', 'D', 'X']) +  # formas geométricas
    labs(
        title='Relação entre Peso (Carat) e Preço (USD) por Corte, Cor e Clareza',
        subtitle='Cada painel representa uma combinação de cor (linhas) e clareza (colunas)',
        x='Peso (em quilates)',
        y='Preço (em dólares)',
        color='Corte',
        shape='Corte'  # legenda para formas
    ) +
    theme_minimal() +
    theme(
        legend_position='bottom',
        text=element_text(size=9),
        figure_size=(14, 10),
        subplots_adjust={'wspace': 0.15, 'hspace': 0.3}
    )
)

# Bom, a principal dificuldade é conseguir comparar todos os 56 painés de gráficos ao mesmo tempo, podendo demorar muito mais tempo para chegar a alguma conclusão, além do tamanho reduzido dos textos e dos gráficos, apesar de conseguirmos visualizar todos os gráficos e difícil de olhar as diferenças entre eles
# Entretanto, de maneira geral se manteve a relação positiva entre preço e peso, porém nota-se algumas variações em alguns painés

